name: Tests

on:
    push:
    pull_request:

jobs:
    phpunit:
        runs-on: ubuntu-latest
    
        strategy:
            fail-fast: false
            matrix:
                php: [7.4, 8.0, 8.1, 8.2, 8.3]
        
        name: PHP ${{ matrix.php }}

        steps:
            # 1. Забираем код из репозитория
          - name: Checkout repository
            uses: actions/checkout@v4

            # 2. Устанавливаем PHP
          - name: Setup PHP
            uses: shivammathur/setup-php@v2
            with:
              php-version: ${{ matrix.php }}
              extensions: mbstring, json
              coverage: none

            # 3. Устанавливаем зависимости
          - name: Install dependencies
            run: composer install --no-interaction --prefer-dist

            # 4. Запускаем тесты
          - name: Run tests
            run: vendor/bin/phpunit
